((forge-dispatch nil)
 (magit-branch nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-log
  ("-n256" "--decorate"))
 (magit-pull nil)
 (magit-push nil)
 (magit-rebase nil)
 (magit-show-refs nil)
 (magit-stash nil)
 (magit-submodule nil))
